name: Maven Package
on:
  push:
    branches:
      – main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      – uses: actions/checkout@v2
      – name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: github
          server-username: GITHUB_USER_REF  # env variable name for username
          server-password: GITHUB_TOKEN_REF
      – name: Build with Maven.
        run: mvn clean install
        env:
          GITHUB_USER_REF: ${{ secrets.GIT_USERNAME }}
          GITHUB_TOKEN_REF: ${{ secrets.GIT_TOKEN }}
